### ISSUE TITLE
Feature Longest Part/Total Length in Summary

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-toolbox-sketchup-plugin#11]
For projects with dimensional lumber (2x4, 2x6, Konstruktionsvollholz, bois de construction), it would be interesting to know the longest part and the total length of each group. Pricelists of this type of wood is usually given in linear meters or feet.

**Comment by bbeaulant** [comment]
Yes I enter the same reflexion. It may be good to create a new type of material for "bois de construction", no ?
Because this kind of material doesn't need the same meta data. No width and thickness increase.

**Comment by mobilarte** [comment]
I converted a model using dimensional lumber, maybe no need to add a new material type. I just set 0 for width and thickness oversize and a single thickness. Obviously the plugin cannot check if the width matches the lumber.

Making "material typ" an extensible plugin would be the luxury version.

**Comment by bbeaulant** [comment]
I think it's not realy a luxury, because this new type of material could be proccess deferently.
For exemple, a _length available_ parameter could be added in cut options. And this parameter doesn't have a lot of sens for solid wood.

**Comment by mobilarte** [comment]
With version 1.3 this issue can be closed as much of the functionality is done. Longest part can be easily read from the detailed parts list.

**Comment by bbeaulant** [comment]
You're right. Issue closed ;)
