### ISSUE TITLE
Window Resizing hides List

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-toolbox-sketchup-plugin#12]
On Window resize, the right side gets sometimes hidden, clicking _generate_ does not resize the content. This appeared recently.

![plugin_ladb](https://cloud.githubusercontent.com/assets/24858423/22032455/d04a810a-dce4-11e6-83c4-ea85c5262d2a.jpg)

**Comment by bbeaulant** [comment]
Yes, I saw it but never take the time to solve it.
This is a problem I solved in the past for www.lairdubois.fr. But I don't remember how ;)

**Comment by bbeaulant** [comment]
Fixed https://github.com/lairdubois/lairdubois-toolbox-sketchup-plugin/commit/0dba9e32686819139a3f997c6e9018398a3edc48
