### ISSUE TITLE
Header in the middle of the page when printing

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-toolbox-sketchup-plugin#13]
When printing the parts list, the sticky header is placed where it was in the scrolling html view.

[test.pdf](https://github.com/lairdubois/lairdubois-toolbox-sketchup-plugin/files/714080/test.pdf)

**Comment by bbeaulant** [comment]
Fixed https://github.com/lairdubois/lairdubois-toolbox-sketchup-plugin/commit/7127086316b8e2f3ccbef76dc0147c97faf18ca6
