### ISSUE TITLE
Cutting parameters not saving

### ISSUE THREAD

**Issue by sheam** [lairdubois/lairdubois-toolbox-sketchup-plugin#23]
Trying to save the cutting parameters for my materials, but it doesn't seem to save them. 

I change a value, hit apply. But then re-open and everything is back to the defaults.

Love this plugin btw.

**Comment by bbeaulant** [comment]
Parameters are stored in the model file (.skp). Then you need to save your model to save those parameters.
I'm glad you love it !

**Comment by sheam** [comment]
Ok,

So I just figured out how to use inches in it (in Canada, we are metric, but all construction is still in feet/inches). This makes it even better.

I see one issue is that I have two different materials for my wood, in order to have the grain going the correct direction in Sketchup. So, Toolbox is treating it as seperate material... Obviously not a bug. One solution would be the option of saying Material A and B are the same. For now, I'll just use the same texture everywhere in sketchup.

I will often make my 2.5" legs out of 3 peices of 1" when the rest of my proect is 1" stock. I tried removing 3" from the available thicknesses, but I get a thickness not available. That is a bit of a tough one to solve... I could compose the leg of 3 parts in  my drawing....

Anyway, this is really a hidden gem. Recommending it to all friends currently using the old cut list.

**Comment by sheam** [comment]
BTW, saving worked after restarting. I think the issue was I had two materials named the same thing.

**Comment by bbeaulant** [comment]
The plugin uses the model unit. Then if your model in in inches, the plugin will display inches.

You don't need to have two materials to have different grain orientation. If it's juste a view problem, use the SU build-in texture orientation tool. But in this case the texture need to be applied on the face itself.

![capture d ecran 2017-09-22 a 18 36 35](https://user-images.githubusercontent.com/156056/30754941-08e1b0a8-9fc5-11e7-82d7-eb91c3e85588.png)
![capture d ecran 2017-09-22 a 18 36 23](https://user-images.githubusercontent.com/156056/30754942-0908c9c2-9fc5-11e7-9f2e-08b394a00855.png)

If you want to orient the piece in the cut list, use the "lock" option in the plugin.

![capture d ecran 2017-09-22 a 18 38 50](https://user-images.githubusercontent.com/156056/30755026-51ee9540-9fc5-11e7-9c02-fec42fcb6178.png)

**Comment by sheam** [comment]
Great, thanks!

**Comment by bbeaulant** [comment]
For a good cut list, you model need to be a reflect of reality. Then if you use 3 pieces to build one, your model need 3 pieces too.

**Comment by sheam** [comment]
Yeah, the issue is this: 

In reality something like this will happen:

1.  I will just barely plane 1/16th off each side of the middle peice (7/8" finished).
2. Plane 1/6th off each outside piece (15/16") to ensure the glue up is flush.
3. Glue the 3 peices together.
4. Plane the outward face another another 1/8" (13/16th finished).
Total thickness is 2.5"

I have the cut list set to add 1/4" for rough dimensions. But this will make the middle piece over 1" so it will think it needs a thicker piece of wood.

The way around it would be to create a difference material for the middle piece, and then tell Toolbox to only at 1/8th for rough dimensions on that material.
