### ISSUE TITLE
Width first in Parts List Columns

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-toolbox-sketchup-plugin#25]
When sawing a large number of birch multiplex, I noticed that it would be nice to be able to display "width" first. This may help to optimize cuts on panel saws, where horizontal cuts are usually done first (pieces cannot be rotated because of grain direction).

**Comment by bbeaulant** [comment]
Hi, sorting on the "width" property" is not enough ?
![Sorting on width property](https://user-images.githubusercontent.com/156056/37149766-83dc5cbc-22cf-11e8-837a-92a66d59b3ac.png)

**Comment by mobilarte** [comment]
It helps, but increases the likelihood of errors, because you always have to read the second column first, then the first column. Happened to us when cutting around 100 pieces from 15 sheets of 2500x 1250.

**Comment by bbeaulant** [comment]
Hi mobilarte, can you check the last commit https://github.com/lairdubois/lairdubois-toolbox-sketchup-plugin/commit/a8ea345e07b9e597510645db9d06eb52e914b991 ?

![capture](https://user-images.githubusercontent.com/156056/37297743-b258bcbe-261e-11e8-805a-43096b3c25b2.png)

**Comment by mobilarte** [comment]
Works perfectly!
