### ISSUE TITLE
Plugin Version Update Error

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-toolbox-sketchup-plugin#28]
In gulpfile.js:
        .pipe(replace(/VERSION = '[0-9.]+(-alpha)?'/g, "VERSION = '" + version + "'"))
instead of:
        .pipe(replace(/VERSION = '[0-9.]+'/g, "VERSION = '" + version + "'"))
otherwise version "1.3.0-alpha" does not get updated in plugin.rb.

**Comment by bbeaulant** [comment]
Outch, you're right ! Bad mistake...
